-- ============================================================================
-- CRA-Systemkorrektur (Fable-Audit 2026-09-04): iso_ids Annex->sequenziell neu
-- gesetzt (67 falsche IDs auf 51 Kontrollen), coverage angepasst, req_en (65)
-- ergaenzt, 6 inhaltliche req_de-Korrekturen. meta.risiko_ids bleibt erhalten
-- (|| merged nur iso_ids/coverage). Idempotent (reine UPDATEs).
-- ============================================================================
BEGIN;

UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-122", "a8-91", "a8-96"], "coverage": "teil"}'::jsonb, req_en = 'Is the product subjected to a vulnerability scan before being placed on the market in order to detect security weaknesses prior to release?' WHERE framework='CRA' AND id='CRA-01.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-31", "a8-122"], "coverage": "teil"}'::jsonb, req_en = 'Are known CVEs checked against all components, including transitive dependencies, in order to uncover known vulnerabilities?' WHERE framework='CRA' AND id='CRA-01.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-32", "a8-121"], "coverage": "teil"}'::jsonb, req_en = 'Is it ensured that no release is shipped with unmitigated critical or high-severity vulnerabilities?' WHERE framework='CRA' AND id='CRA-01.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-91", "a8-95"], "coverage": "teil"}'::jsonb, req_en = 'Are the results of the vulnerability assessment documented and included in the product''s technical documentation?' WHERE framework='CRA' AND id='CRA-01.4';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-23"], "coverage": "teil"}'::jsonb, req_en = 'Is it ensured that no factory default passwords are used and that a password change is enforced at initial commissioning?' WHERE framework='CRA' AND id='CRA-02.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-123", "a8-35"], "coverage": "teil"}'::jsonb, req_en = 'Are unneeded ports and services already disabled ex works in order to minimise the attack surface in the delivered state?' WHERE framework='CRA' AND id='CRA-02.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-69", "a8-142"], "coverage": "teil"}'::jsonb, req_en = 'Is encrypted communication enabled by default in the delivered state, without users first having to switch it on?' WHERE framework='CRA' AND id='CRA-02.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Does a factory reset reliably restore the product to a secure original state?' WHERE framework='CRA' AND id='CRA-02.4';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-88", "a8-115"], "coverage": "teil"}'::jsonb, req_en = 'Is authentication required for all privileged functions of the product before they can be executed?' WHERE framework='CRA' AND id='CRA-03.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-36", "a5-44", "a5-98"], "coverage": "teil"}'::jsonb, req_en = 'Is identity and access management implemented according to the least-privilege principle, so that users receive only the permissions they need?' WHERE framework='CRA' AND id='CRA-03.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-21", "a8-88"], "coverage": "teil"}'::jsonb, req_en = 'Does the product provide protection against brute-force and replay attacks on authentication?' WHERE framework='CRA' AND id='CRA-03.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-44", "a8-77"], "coverage": "teil"}'::jsonb, req_en = 'Are confidential data stored encrypted (at rest) so that they remain protected against unauthorised access to the storage medium?' WHERE framework='CRA' AND id='CRA-04.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-69", "a8-142"], "coverage": "teil"}'::jsonb, req_en = 'Are data encrypted in transit using state-of-the-art mechanisms in order to prevent eavesdropping and manipulation?' WHERE framework='CRA' AND id='CRA-04.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-78", "a8-79", "a8-80"], "coverage": "teil"}'::jsonb, req_en = 'Is key management clearly defined and are cryptographic keys adequately protected?' WHERE framework='CRA' AND id='CRA-04.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-64"], "coverage": "teil"}'::jsonb, req_en = 'Is the integrity of firmware and software verified by signatures in order to detect unauthorised or manipulated versions?' WHERE framework='CRA' AND id='CRA-05.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-33", "a8-140"], "coverage": "teil"}'::jsonb, req_en = 'Is it ensured that unauthorised changes to configuration or commands are prevented or reliably detected?' WHERE framework='CRA' AND id='CRA-05.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-82", "a8-55"], "coverage": "teil"}'::jsonb, req_en = 'Is effective tamper protection implemented for security-relevant data?' WHERE framework='CRA' AND id='CRA-05.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-83", "a8-86"], "coverage": "teil"}'::jsonb, req_en = 'Is it ensured that only data (personal or other) that are adequate, relevant and limited to what is necessary for the intended purpose are processed?', req_de = 'Werden nur die für den Zweck notwendigen Daten — personenbezogene und andere — verarbeitet, sodass die Verarbeitung auf das Erforderliche begrenzt ist?' WHERE framework='CRA' AND id='CRA-06.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-14", "a5-36"], "coverage": "teil"}'::jsonb, req_en = 'Is data access limited to what is required for the respective task?' WHERE framework='CRA' AND id='CRA-06.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-52", "a8-24"], "coverage": "teil"}'::jsonb, req_en = 'Do the product''s essential and basic functions remain available, through appropriate resilience measures, even under overload or denial-of-service attacks and after an incident?' WHERE framework='CRA' AND id='CRA-07.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-88", "a8-132"], "coverage": "teil"}'::jsonb, req_en = 'Are rate limiting and filtering against abusive requests in place to fend off overload caused by malicious traffic?' WHERE framework='CRA' AND id='CRA-07.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Is it ensured that the product has no negative impact on the availability of services provided by other devices or networks, for example through unnecessary broadcasts?' WHERE framework='CRA' AND id='CRA-08.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-132", "a8-67"], "coverage": "teil"}'::jsonb, req_en = 'Are the product''s outbound connections controlled and documented so that unwanted traffic remains traceable?' WHERE framework='CRA' AND id='CRA-08.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-123", "a8-33"], "coverage": "teil"}'::jsonb, req_en = 'Are the product''s external interfaces minimised to what is necessary and fully documented?' WHERE framework='CRA' AND id='CRA-09.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-123", "a8-35"], "coverage": "teil"}'::jsonb, req_en = 'Is it ensured that unused functions and libraries are removed or disabled in order to reduce the attack surface?' WHERE framework='CRA' AND id='CRA-09.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-92"], "coverage": "teil"}'::jsonb, req_en = 'Has an attack surface analysis been carried out to systematically identify possible entry points?' WHERE framework='CRA' AND id='CRA-09.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-123"], "coverage": "teil"}'::jsonb, req_en = 'Are exploitation mitigation techniques such as ASLR, DEP or sandboxing enabled in order to make the exploitation of vulnerabilities more difficult?' WHERE framework='CRA' AND id='CRA-10.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Are security-relevant memory areas effectively protected against unauthorised access and manipulation?' WHERE framework='CRA' AND id='CRA-10.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-125", "a8-54"], "coverage": "teil"}'::jsonb, req_en = 'Are security-relevant events such as access, modifications and errors recorded so that incidents can be reconstructed?' WHERE framework='CRA' AND id='CRA-11.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-55", "a8-57"], "coverage": "teil"}'::jsonb, req_en = 'Are the logs tamper-resistant and can they be exported for analysis?' WHERE framework='CRA' AND id='CRA-11.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-128", "a8-125"], "coverage": "teil"}'::jsonb, req_en = 'Is the retention period of the logs clearly defined?' WHERE framework='CRA' AND id='CRA-11.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-64", "a8-66"], "coverage": "teil"}'::jsonb, req_en = 'Does the product have a secure update mechanism with signed updates in order to prevent manipulated updates?' WHERE framework='CRA' AND id='CRA-12.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Where applicable, are automatic security updates installed within an appropriate timeframe and enabled by default, with a clear and easy-to-use opt-out mechanism, notification of available updates and the option to temporarily postpone them, and is the opt-out documented for users?', req_de = 'Sind, soweit anwendbar, automatische Sicherheitsupdates standardmäßig aktiviert, mit klarer Opt-out-Möglichkeit, Benachrichtigung über verfügbare Updates und Möglichkeit, ein Update aufzuschieben?' WHERE framework='CRA' AND id='CRA-12.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-105"], "coverage": "teil"}'::jsonb, req_en = 'After a failed update, is a rollback or recovery to a functional state possible?' WHERE framework='CRA' AND id='CRA-12.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-36"], "coverage": "teil"}'::jsonb, req_en = 'Can users securely and easily remove all data and settings on a permanent basis?', req_de = 'Können Nutzer alle Daten und Einstellungen des Produkts sicher und dauerhaft löschen (nicht nur personenbezogene Daten)?' WHERE framework='CRA' AND id='CRA-13.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-116"], "coverage": "teil"}'::jsonb, req_en = 'Where data can be transferred to other products or systems, is this transfer performed in a secure manner (and, where offered, in a commonly used, reusable format)?' WHERE framework='CRA' AND id='CRA-13.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Are vulnerabilities found in integrated components (incl. open source) reported to the manufacturing/maintaining entity, and is a developed fix (code/docs, where appropriate machine-readable) shared with the maintainer? (CRA Art. 13(6))' WHERE framework='CRA' AND id='CRA-13.6';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Is a machine-readable software bill of materials (SBOM) produced that covers at least the product''s top-level dependencies?' WHERE framework='CRA' AND id='CRA-14.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Is it ensured that the SBOM is updated whenever components change?' WHERE framework='CRA' AND id='CRA-14.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Is the SBOM provided in a commonly used, standardised format such as CycloneDX or SPDX?' WHERE framework='CRA' AND id='CRA-14.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-31", "a8-30"], "coverage": "teil"}'::jsonb, req_en = 'Are vulnerabilities identified in your products assessed without delay and prioritised by risk, so that the most critical ones are handled first?' WHERE framework='CRA' AND id='CRA-15.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-32"], "coverage": "teil"}'::jsonb, req_en = 'Are security updates to remediate identified vulnerabilities developed and made available to users without delay?' WHERE framework='CRA' AND id='CRA-15.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-122", "a8-121"], "coverage": "teil"}'::jsonb, req_en = 'Is the remediation of vulnerabilities documented in such a way that the measures taken can later be traced and verified?' WHERE framework='CRA' AND id='CRA-15.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-96", "a8-91", "a8-95"], "coverage": "teil"}'::jsonb, req_en = 'Are effective and regular security tests, including penetration tests, carried out to actively uncover vulnerabilities in your products?' WHERE framework='CRA' AND id='CRA-16.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-122", "a8-95"], "coverage": "teil"}'::jsonb, req_en = 'Are the results of security tests systematically evaluated and the findings demonstrably addressed?' WHERE framework='CRA' AND id='CRA-16.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Once a security update is available, is information about fixed vulnerabilities shared and publicly disclosed so that users are informed about known security issues and their remediation?' WHERE framework='CRA' AND id='CRA-17.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Do your security advisories contain a description of the vulnerability, the affected product versions, the impact and severity, and clear, accessible remediation guidance?' WHERE framework='CRA' AND id='CRA-17.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-62"], "coverage": "teil"}'::jsonb, req_en = 'Has a coordinated vulnerability disclosure (CVD) policy been put in place, enforced and made publicly accessible?' WHERE framework='CRA' AND id='CRA-18.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-62", "a5-66"], "coverage": "teil"}'::jsonb, req_en = 'Are the timelines and the workflow of the disclosure process for reported vulnerabilities clearly defined?' WHERE framework='CRA' AND id='CRA-18.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-62"], "coverage": "teil"}'::jsonb, req_en = 'Is there a publicly reachable reporting channel, such as a contact address or security.txt, through which vulnerabilities in the product and in its third-party components can be reported?' WHERE framework='CRA' AND id='CRA-19.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-65", "a5-62"], "coverage": "teil"}'::jsonb, req_en = 'Are incoming vulnerability reports tracked, and do reporters receive feedback on the handling of their report?' WHERE framework='CRA' AND id='CRA-19.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-69", "a8-64"], "coverage": "teil"}'::jsonb, req_en = 'Are updates distributed exclusively via a secure, authenticated channel in order to prevent manipulation during delivery?' WHERE framework='CRA' AND id='CRA-20.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a8-64"], "coverage": "teil"}'::jsonb, req_en = 'Is the integrity of updates verified before installation to ensure they have not been altered or forged?' WHERE framework='CRA' AND id='CRA-20.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Are security patches provided to users free of charge, so that no additional costs arise for the remediation of vulnerabilities (unless otherwise agreed with a business user for a tailor-made product)?' WHERE framework='CRA' AND id='CRA-21.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Has the support period been determined and documented so that it reflects the expected time in use (at least five years unless the product is expected to be in use for less), and is it clearly communicated to users?', req_de = 'Ist der Supportzeitraum anhand der erwarteten Nutzungsdauer bestimmt — mindestens 5 Jahre, es sei denn die erwartete Nutzungsdauer ist kürzer — und sind die Bestimmungskriterien in der technischen Dokumentation festgehalten?' WHERE framework='CRA' AND id='CRA-21.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Has the conformity assessment procedure appropriate to the product class (internal control or third-party assessment) been properly carried out?' WHERE framework='CRA' AND id='CRA-22.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Has the CE marking been affixed to the product and is the corresponding EU declaration of conformity available?' WHERE framework='CRA' AND id='CRA-22.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'For class I important products where harmonised standards, common specifications or European cybersecurity certification schemes have not been applied or applied only in part, is a notified body involved in the conformity assessment (module B+C or H)?' WHERE framework='CRA' AND id='CRA-22.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Has the technical documentation been drawn up in accordance with Annex VII of the Cyber Resilience Act?' WHERE framework='CRA' AND id='CRA-23.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Does the technical documentation contain the cybersecurity risk assessment, the SBOM and the support period information, and is it kept up to date?' WHERE framework='CRA' AND id='CRA-23.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-96", "a5-11"], "coverage": "teil"}'::jsonb, req_en = 'Are actively exploited vulnerabilities notified within 24 hours as an early warning, simultaneously to the CSIRT designated as coordinator and to ENISA, via the single reporting platform?', req_de = 'Werden aktiv ausgenutzte Schwachstellen binnen 24 Stunden als Frühwarnung gleichzeitig an das zuständige CSIRT und ENISA über die zentrale Meldeplattform gemeldet?' WHERE framework='CRA' AND id='CRA-24.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-96", "a5-66"], "coverage": "teil"}'::jsonb, req_en = 'Is a full vulnerability notification of the actively exploited vulnerability submitted to the competent bodies within 72 hours?' WHERE framework='CRA' AND id='CRA-24.2';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["a5-67", "a5-96"], "coverage": "teil"}'::jsonb, req_en = 'After handling is complete, is a final report on the vulnerability or incident submitted within the deadline (14 days after a corrective measure is available; one month after the incident notification)?' WHERE framework='CRA' AND id='CRA-24.3';
UPDATE public.controls SET meta = meta || '{"iso_ids": ["c7-10"], "coverage": "teil"}'::jsonb, req_en = 'Are impacted users actively informed about actively exploited vulnerabilities and severe incidents and about the corrective and mitigating measures they can take?' WHERE framework='CRA' AND id='CRA-24.4';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Is the product correctly classified, i.e. as a default product, an important product of class I or II under Annex III, or a critical product under Annex IV?', req_de = 'Ist das Produkt korrekt eingestuft — Standardprodukt, wichtiges Produkt (Anhang III, Klasse I/II) oder kritisches Produkt (Anhang IV)?' WHERE framework='CRA' AND id='CRA-25.1';
UPDATE public.controls SET meta = meta || '{"iso_ids": [], "coverage": "delta"}'::jsonb, req_en = 'Has the conformity assessment route appropriate to the product class been selected, and is this choice justified in a traceable manner?' WHERE framework='CRA' AND id='CRA-25.2';

COMMIT;
