-- ============================================================================
-- 17 neue CRA-Kontrollen (CRA-26..33): Risikobewertung Art.13(2-4), Support-
-- zeitraum/Enddatum 13(8-11)/(19), DoC/CE Annex V + Art.28/30, Nutzerinfo
-- Annex II, Komponenten-Sorgfalt 13(5), schwerer Vorfall Art.14(3-7), Opt-out-
-- Logging, Security/Feature-Trennung, Korrekturmassnahmen 13(21). Idempotent.
-- ============================================================================
BEGIN;

INSERT INTO public.controls (framework,id,req_de,req_en,meta) VALUES
  ('CRA','CRA-26.1','Wird für das Produkt eine Cybersicherheits-Risikobewertung durchgeführt (Zweckbestimmung, vernünftigerweise vorhersehbare Nutzung, Einsatzbedingungen, zu schützende Werte, erwartete Nutzungsdauer) und werden ihre Ergebnisse in Planung, Design, Entwicklung, Produktion, Auslieferung und Wartung berücksichtigt?','Is a cybersecurity risk assessment carried out for the product (intended purpose, reasonably foreseeable use, conditions of use, assets to be protected, expected time in use), and are its results taken into account during planning, design, development, production, delivery and maintenance?','{"coverage": "teil", "iso_ids": ["c6-05", "c6-06", "a5-19"], "risiko_ids": ["DR-CRA-26.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-26.2','Ist die Risikobewertung dokumentiert, gibt sie je Anforderung nach Anhang I Teil I Nr. 2 (a)–(m) an, ob und wie sie anwendbar und umgesetzt ist (mit Begründung bei Nichtanwendbarkeit), beschreibt sie die Umsetzung von Teil I Nr. 1 und Teil II, ist sie Teil der technischen Dokumentation und wird sie über den Supportzeitraum aktualisiert (inkl. bekannt gewordener Schwachstellen und Dritt-Informationen)?','Is the risk assessment documented, does it indicate for each requirement under Annex I Part I point 2 (a)–(m) whether and how it applies and is implemented (with justification where not applicable), does it describe how Part I point 1 and Part II are applied, is it part of the technical documentation, and is it updated throughout the support period (including newly known vulnerabilities and third-party information)?','{"coverage": "teil", "iso_ids": ["c6-07", "c8-05", "c8-06"], "risiko_ids": ["DR-CRA-26.2"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-27.1','Wird das Enddatum des Supportzeitraums (mindestens Monat und Jahr) zum Zeitpunkt des Kaufs klar, verständlich und leicht zugänglich angegeben (soweit anwendbar auf dem Produkt, der Verpackung oder digital) und werden Nutzer, soweit technisch machbar, über das Erreichen des Support-Endes benachrichtigt?','Is the end date of the support period (at least month and year) specified clearly, understandably and in an easily accessible manner at the time of purchase (where applicable on the product, its packaging or by digital means), and are users, where technically feasible, notified when the product reaches the end of its support period?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-27.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-27.2','Bleibt jedes während des Supportzeitraums bereitgestellte Sicherheitsupdate nach Veröffentlichung mindestens 10 Jahre oder für den Rest des Supportzeitraums (je nachdem, was länger ist) verfügbar, und werden Nutzer bei öffentlichen Archiven historischer Versionen klar über die Risiken nicht unterstützter Software informiert?','Does every security update made available during the support period remain available for at least 10 years after issue or for the remainder of the support period, whichever is longer, and where public archives of historical versions are maintained, are users clearly informed about the risks of using unsupported software?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-27.2"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-28.1','Enthält die EU-Konformitätserklärung alle Pflichtangaben nach Anhang V (Produktidentifikation, Hersteller, alleinige Verantwortung, Konformitätsaussage, angewandte harmonisierte Normen/Spezifikationen/Zertifizierungen, ggf. notifizierte Stelle und Zertifikat), wird sie bei Bedarf aktualisiert, in den Sprachen des Mitgliedstaats bereitgestellt, bei mehreren Rechtsakten als eine Erklärung ausgestellt und – falls eine vereinfachte Erklärung beiliegt – mit der exakten Internetadresse der vollständigen Erklärung versehen?','Does the EU declaration of conformity contain all mandatory elements under Annex V (product identification, manufacturer, sole responsibility, statement of conformity, harmonised standards/specifications/certifications applied, notified body and certificate where applicable), is it updated as appropriate, provided in the languages required by the Member State, issued as a single declaration where several Union acts apply, and – where a simplified declaration accompanies the product – does it state the exact internet address of the full declaration?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-28.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-28.2','Werden technische Dokumentation und EU-Konformitätserklärung mindestens 10 Jahre nach Inverkehrbringen oder für den Supportzeitraum (je nachdem, was länger ist) für die Marktüberwachungsbehörden bereitgehalten, und ist ein Verfahren definiert, um auf begründetes Verlangen alle Informationen in einer für die Behörde leicht verständlichen Sprache vorzulegen und bei Maßnahmen zu kooperieren?','Are the technical documentation and the EU declaration of conformity kept at the disposal of market surveillance authorities for at least 10 years after placing on the market or for the support period, whichever is longer, and is a procedure defined to provide, upon reasoned request, all information in a language easily understood by the authority and to cooperate on any measures?','{"coverage": "teil", "iso_ids": ["c7-16", "a5-82"], "risiko_ids": ["DR-CRA-28.2"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-28.3','Ist ein Verfahren etabliert, das bei Kenntnis oder Grund zur Annahme einer Nichtkonformität des Produkts oder der Prozesse unverzüglich Korrekturmaßnahmen auslöst (Konformität herstellen, Rücknahme oder Rückruf), und wird die Konformität bei Serienfertigung auch bei Änderungen an Entwicklung, Design, Produkt oder anwendbaren Normen/Spezifikationen fortlaufend sichergestellt?','Is a procedure established that, upon knowledge or reason to believe that the product or the manufacturer''s processes are not in conformity, immediately triggers corrective measures (bringing into conformity, withdrawal or recall), and is conformity maintained for series production, including when the development or production process, the product design or the applicable standards/specifications change?','{"coverage": "teil", "iso_ids": ["c10-02", "c10-03", "a8-139"], "risiko_ids": ["DR-CRA-28.3"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-29.1','Liegen dem Produkt (in Papier- oder elektronischer Form, in verständlicher Sprache) die Nutzerinformationen nach Anhang II bei: Hersteller mit Kontaktdaten, zentrale Anlaufstelle für Schwachstellenmeldungen und Fundstelle der CVD-Policy, eindeutige Produktidentifikation, Zweckbestimmung inkl. Sicherheitsumgebung, wesentliche Funktionen und Sicherheitseigenschaften, bekannte oder vorhersehbare Umstände mit erheblichem Cybersicherheitsrisiko, Internetadresse der Konformitätserklärung, Art des Supports und Support-Enddatum sowie ggf. Fundstelle der SBOM – und bleiben sie mindestens 10 Jahre bzw. für den Supportzeitraum verfügbar (online: zugänglich und nutzerfreundlich)?','Is the product accompanied (in paper or electronic form, in an easily understood language) by the user information under Annex II: manufacturer with contact details, single point of contact for vulnerability reports and location of the CVD policy, unique product identification, intended purpose including the security environment, essential functionalities and security properties, known or foreseeable circumstances leading to significant cybersecurity risks, internet address of the declaration of conformity, type of support and end date of the support period, and where applicable the location of the SBOM – and does this information remain available for at least 10 years or the support period (online: accessible and user-friendly)?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-29.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-29.2','Enthalten die Nutzerinformationen detaillierte Anleitungen (oder einen Verweis darauf) zu: notwendigen Maßnahmen bei Erstinbetriebnahme und über die Lebensdauer für sichere Nutzung; Auswirkungen von Produktänderungen auf die Datensicherheit; Installation sicherheitsrelevanter Updates; sicherer Außerbetriebnahme inkl. sicherer Datenlöschung; Abschalten der automatischen Sicherheitsupdate-Installation; sowie – bei zur Integration bestimmten Produkten – den Informationen, die der Integrator zur Erfüllung von Anhang I und Anhang VII benötigt?','Do the user information and instructions contain detailed instructions (or a reference to them) on: the measures necessary at initial commissioning and throughout the lifetime for secure use; how changes to the product can affect the security of data; how security-relevant updates can be installed; secure decommissioning including secure removal of user data; how the default automatic installation of security updates can be turned off; and – for products intended for integration – the information the integrator needs to comply with Annex I and Annex VII?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-29.2"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-29.3','Trägt das Produkt eine Typen-, Chargen- oder Seriennummer (bzw. ein anderes Identifikationsmerkmal) und sind Name/Handelsname/Marke des Herstellers sowie Postanschrift, E-Mail oder anderer digitaler Kontakt und ggf. Website auf dem Produkt, der Verpackung oder einem Begleitdokument angegeben?','Does the product bear a type, batch or serial number or other element allowing its identification, and are the manufacturer''s name, registered trade name or trademark, postal address, email address or other digital contact and, where applicable, website indicated on the product, its packaging or an accompanying document?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-29.3"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-30.1','Wird bei der Integration von Drittkomponenten – einschließlich Free-and-Open-Source-Software, die nicht im Rahmen einer Geschäftstätigkeit bereitgestellt wird – eine dokumentierte Sorgfaltsprüfung durchgeführt (Sicherheitsniveau, Wartungs-/Supportstatus, bekannte Schwachstellen, Update-Fähigkeit, Lizenz, Vertrauenswürdigkeit der Quelle), sodass die Komponenten die Cybersicherheit des Produkts nicht beeinträchtigen?','When integrating third-party components – including free and open-source software not made available in the course of a commercial activity – is documented due diligence exercised (security posture, maintenance/support status, known vulnerabilities, updatability, licence, trustworthiness of the source) so that those components do not compromise the cybersecurity of the product?','{"coverage": "teil", "iso_ids": ["a5-54", "a5-48", "a5-81"], "risiko_ids": ["DR-CRA-30.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-31.1','Werden schwerwiegende Vorfälle mit Auswirkung auf die Produktsicherheit (Beeinträchtigung der Fähigkeit, Verfügbarkeit/Authentizität/Integrität/Vertraulichkeit sensibler Daten oder Funktionen zu schützen, oder Einschleusung/Ausführung von Schadcode) gleichzeitig an das koordinierende CSIRT und ENISA über die zentrale Meldeplattform gemeldet – Frühwarnung binnen 24 h (inkl. Verdacht auf rechtswidrige/böswillige Handlung und betroffene Mitgliedstaaten), Vorfallmeldung binnen 72 h (Art, erste Bewertung, ergriffene und nutzerseitige Maßnahmen) und Abschlussbericht binnen eines Monats nach der Vorfallmeldung?','Are severe incidents having an impact on the security of the product (negatively affecting the ability to protect availability, authenticity, integrity or confidentiality of sensitive or important data or functions, or leading to the introduction or execution of malicious code) notified simultaneously to the CSIRT designated as coordinator and to ENISA via the single reporting platform – an early warning within 24 hours (including whether unlawful or malicious acts are suspected and the Member States concerned), an incident notification within 72 hours (nature, initial assessment, corrective and user-side measures) and a final report within one month after the incident notification?','{"coverage": "teil", "iso_ids": ["a5-96", "a5-66", "a5-61"], "risiko_ids": ["DR-CRA-31.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-31.2','Ist die Meldeorganisation für Art. 14 festgelegt: zuständiges koordinierendes CSIRT nach Hauptniederlassung (bzw. Reihenfolge nach Art. 14(7) ohne EU-Niederlassung), Zugang und Rollen für die zentrale Meldeplattform nach Art. 16, Zuständigkeiten und Eskalation zur Fristeinhaltung (24 h/72 h), Bereitstellung von Zwischenberichten auf Anfrage des CSIRT, und Kennzeichnung der Sensibilität gemeldeter Informationen?','Is the reporting organisation for Article 14 defined: the competent CSIRT designated as coordinator according to the main establishment (or the order under Art. 14(7) without an EU establishment), access and roles for the single reporting platform under Art. 16, responsibilities and escalation to meet the 24 h/72 h deadlines, provision of intermediate reports upon CSIRT request, and indication of the sensitivity of notified information?','{"coverage": "teil", "iso_ids": ["a5-97", "a5-11", "a5-129"], "risiko_ids": ["DR-CRA-31.2"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-32.1','Bietet das Produkt Nutzern einen Opt-out-Mechanismus für die Aufzeichnung und Überwachung interner Aktivitäten (Zugriffe auf und Änderungen an Daten, Diensten oder Funktionen)?','Does the product provide users with an opt-out mechanism for the recording and monitoring of relevant internal activity (access to or modification of data, services or functions)?','{"coverage": "teil", "iso_ids": ["a8-126"], "risiko_ids": ["DR-CRA-32.1"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-32.2','Werden Sicherheitsupdates, wo technisch machbar, getrennt von Funktionsupdates bereitgestellt, sodass Nutzer Sicherheitskorrekturen ohne erzwungene Funktionsänderungen einspielen können?','Where technically feasible, are security updates provided separately from functionality updates, so that users can apply security fixes without being forced to accept functional changes?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-32.2"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-32.3','Meldet das Produkt möglichen unbefugten Zugriff sowie erkannte Integritätsverletzungen (Korruption von Daten, Befehlen, Programmen oder Konfiguration) an den Nutzer bzw. Betreiber, etwa durch Alarme, Statusanzeigen oder Ereignismeldungen?','Does the product report possible unauthorised access and detected integrity violations (corruption of data, commands, programs or configuration) to the user or operator, for example through alerts, status indicators or event notifications?','{"coverage": "teil", "iso_ids": ["a8-58"], "risiko_ids": ["DR-CRA-32.3"], "n_risiken": 1}'::jsonb),
  ('CRA','CRA-33.1','Ist ein Verfahren festgelegt, um bei Einstellung der Geschäftstätigkeit vor deren Wirksamwerden die zuständigen Marktüberwachungsbehörden und – mit allen verfügbaren Mitteln und soweit möglich – die Nutzer der in Verkehr gebrachten Produkte über die bevorstehende Einstellung zu informieren?','Is a procedure defined to inform, before a cessation of operations takes effect, the relevant market surveillance authorities and – by any means available and to the extent possible – the users of the products placed on the market about the impending cessation of operations?','{"coverage": "delta", "iso_ids": [], "risiko_ids": ["DR-CRA-33.1"], "n_risiken": 1}'::jsonb)
ON CONFLICT (framework,id) DO UPDATE
  SET req_de=EXCLUDED.req_de, req_en=EXCLUDED.req_en, meta=EXCLUDED.meta;

-- Verknuepfungen Kontrolle->Risiko stehen in cra_risk_texts.sql (Schritt 3i),
-- NACH dem Anlegen der Risiken. Hier standen sie vorher auch — vor den
-- Risiken: der Fremdschluessel control_risk_risk_id_fkey liess die ganze
-- Transaktion scheitern, und 3i scheiterte danach am fehlenden Control.
-- Beide Dateien liefen im Deploy (|| true) still ins Leere; lokal
-- nachgestellt am 19.09.2026. Die 17 Verknuepfungen sind in 3i vollstaendig
-- enthalten (geprueft: Teilmenge der 83).

COMMIT;
