GRANT EXECUTE ON FUNCTION public.get_org_owner_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_org_role(uuid, uuid, org_role[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.in_same_org(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_lecturer(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_lecturer_org(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_org_member(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_org_owner(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_premium(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_student(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_account_suspended(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.org_member_count(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.org_pending_invite_count(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.org_total_seat_count(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.org_seat_limit(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.get_org_owner_id(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_user_org_id(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.has_org_role(uuid, uuid, org_role[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.in_same_org(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_lecturer(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_lecturer_org(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_org_member(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_org_owner(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_premium(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_student(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_account_suspended(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.org_member_count(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.org_pending_invite_count(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.org_total_seat_count(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.org_seat_limit(uuid) TO service_role;