
INSERT INTO public.frameworks (code, name_de, name_en, sort_order, color, uses_maturity, role) VALUES
  ('ISO27017', 'ISO/IEC 27017 (Cloud)', 'ISO/IEC 27017 (Cloud)', 170, '#0EA5E9', true, 'spoke'),
  ('ISO27018', 'ISO/IEC 27018 (PII Public Cloud)', 'ISO/IEC 27018 (PII Public Cloud)', 175, '#0284C7', true, 'spoke'),
  ('TR03183',  'BSI TR-03183 (CRA-technisch)', 'BSI TR-03183 (CRA technical)', 180, '#F59E0B', true, 'delta')
ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;

INSERT INTO public.controls (framework, id, req_de, req_en, effort_pt, meta) VALUES
  ('TISAX','TISAX-1.6.1','Informationssicherheits-Risikomanagement gemaess ISA 6.0.','Information security risk management per ISA 6.0.',3,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §1.6.1 — IS-Risikomanagement','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-4.2.1','Klassifizierung von Informationen mit definierten Labels.','Information classification with defined labels.',2,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §4.2.1 — Informationsklassifizierung','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-5.2.4','Physische Sicherheit: Werkschutz, Zutrittskontrolle, besucherbegleitete Bereiche.','Physical security: guards, access control, escorted visitor areas.',3,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §5.2.4 — Physische Sicherheit','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-8.2.1','Prototypenschutz: Kennzeichnung, Transport, Fotoverbot, geschuetzte Bereiche.','Prototype protection: labelling, transport, no-photo, protected zones.',4,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §8.2.1 — Prototypenschutz','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-8.2.2','Prototypen-Testfahrzeuge: Tarnung, GPS-Tracking, definierte Teststrecken.','Prototype test vehicles: camouflage, GPS tracking, defined routes.',3,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §8.2.2 — Prototypen-Testfahrzeuge','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-8.2.3','Prototypen-Events: NDA-Pflicht, Fotoverbot, kontrollierte Zugaenge.','Prototype events: NDA, photo ban, controlled access.',2,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §8.2.3 — Events mit Prototypen','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','SOLL')),
  ('TISAX','TISAX-6.1.2','Datenschutz-Vertragsklauseln bei Auftragsdatenverarbeitung (AVV).','Data protection contract clauses for processors (DPA).',2,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §6.1.2 — Auftragsverarbeitung','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-1.2.4','Assessment-Level (AL2/AL3): Selbstauskunft plus vor-Ort-Pruefung.','Assessment level AL2/AL3: self-assessment plus on-site audit.',2,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §1.2.4 — Assessment Level','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-1.4.1','Wiederholungspruefung alle 3 Jahre plus jaehrliches Selbst-Assessment.','Recertification every 3 years + annual self-assessment.',1,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §1.4.1 — Wiederholungspruefung','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TISAX','TISAX-1.5.1','Corrective Action Plan (CAP) bei Non-Conformities binnen 90 Tagen.','Corrective Action Plan for non-conformities within 90 days.',2,
   jsonb_build_object('coverage','delta','ref','TISAX ISA 6.0 §1.5.1 — CAP','quelle','https://portal.enx.com/de-DE/TISAX/','stufe','MUSS')),
  ('TR03183','TR03183-2.1','SBOM im maschinenlesbaren Format (CycloneDX oder SPDX) bereitstellen.','Provide SBOM in machine-readable format (CycloneDX or SPDX).',3,
   jsonb_build_object('coverage','delta','ref','BSI TR-03183 Teil 2 §4.1 — SBOM-Format','quelle','https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/tr03183_node.html','stufe','MUSS')),
  ('TR03183','TR03183-2.2','SBOM mit vollstaendigen Metadaten: Autor, Timestamp, Toolchain, Lizenzen.','SBOM with complete metadata: author, timestamp, toolchain, licences.',2,
   jsonb_build_object('coverage','delta','ref','BSI TR-03183 Teil 2 §4.2 — SBOM-Metadaten','quelle','https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/tr03183_node.html','stufe','MUSS')),
  ('TR03183','TR03183-2.3','Transitiver Dependency-Baum in SBOM (alle indirekten Abhaengigkeiten).','Transitive dependency tree in SBOM (all indirect dependencies).',3,
   jsonb_build_object('coverage','delta','ref','BSI TR-03183 Teil 2 §4.3 — Transitivitaet','quelle','https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/tr03183_node.html','stufe','MUSS')),
  ('TR03183','TR03183-3.1','Coordinated Vulnerability Disclosure Policy nach ISO 29147 veroeffentlichen.','Publish Coordinated Vulnerability Disclosure Policy per ISO 29147.',2,
   jsonb_build_object('coverage','delta','ref','BSI TR-03183 Teil 3 §3 — CVD Policy','quelle','https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/tr03183_node.html','stufe','MUSS')),
  ('TR03183','TR03183-3.2','Vulnerability-Meldeformular mit PGP-Key und definierter Antwortzeit.','Vulnerability reporting form with PGP key and defined response time.',2,
   jsonb_build_object('coverage','delta','ref','BSI TR-03183 Teil 3 §4 — Meldekanaele','quelle','https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/tr03183_node.html','stufe','MUSS')),
  ('TR03183','TR03183-3.3','CSAF-2.0-basierte Security Advisories fuer Kunden.','CSAF 2.0-based security advisories for customers.',3,
   jsonb_build_object('coverage','delta','ref','BSI TR-03183 Teil 3 §5 — CSAF Advisories','quelle','https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/tr03183_node.html','stufe','SOLL')),
  ('ISO27017','ISO27017-CLD.6.3.1','Rollen und Verantwortlichkeiten zwischen Cloud-Kunde und -Provider vertraglich definieren.','Define contractual roles between cloud customer and provider.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.6.3.1 — Rollen Cloud-Kunde/-Provider','quelle','https://www.iso.org/standard/43757.html','stufe','MUSS')),
  ('ISO27017','ISO27017-CLD.8.1.5','Rueckgabe, Uebertragung und sichere Loeschung von Kundendaten bei Vertragsende.','Return, transfer and secure deletion of customer data at contract end.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.8.1.5 — Exit-Management','quelle','https://www.iso.org/standard/43757.html','stufe','MUSS')),
  ('ISO27017','ISO27017-CLD.9.5.1','Trennung virtueller Umgebungen zwischen Mandanten (Multi-Tenant-Isolation).','Segregation of virtual environments between tenants.',4,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.9.5.1 — Multi-Tenant Isolation','quelle','https://www.iso.org/standard/43757.html','stufe','MUSS')),
  ('ISO27017','ISO27017-CLD.9.5.2','Haerten virtueller Maschinen: Baseline-Configs, Patch-Level, deaktivierte Default-Konten.','Harden virtual machines: baselines, patch level, disabled defaults.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.9.5.2 — VM Hardening','quelle','https://www.iso.org/standard/43757.html','stufe','MUSS')),
  ('ISO27017','ISO27017-CLD.12.1.5','Administrative Cloud-Operationen mit MFA, Logging und Peer-Review.','Administrative cloud operations with MFA, logging and peer review.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.12.1.5 — Admin Ops','quelle','https://www.iso.org/standard/43757.html','stufe','MUSS')),
  ('ISO27017','ISO27017-CLD.12.4.5','Monitoring des Cloud-Service durch den Kunden (Log-Zugriff, Metriken).','Customer monitoring of cloud service (log access, metrics).',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.12.4.5 — Customer Monitoring','quelle','https://www.iso.org/standard/43757.html','stufe','MUSS')),
  ('ISO27017','ISO27017-CLD.13.1.4','Netzwerk-Alignment zwischen Cloud-Provider- und Kunden-Sicherheitszonen.','Network alignment between provider and customer security zones.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.13.1.4 — Netzwerk-Alignment','quelle','https://www.iso.org/standard/43757.html','stufe','SOLL')),
  ('ISO27017','ISO27017-CLD.10.1.1','Kunden-managed Encryption Keys (BYOK/HYOK) fuer sensible Daten.','Customer-managed encryption keys (BYOK/HYOK) for sensitive data.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27017:2015 CLD.10.1.1 — Kryptographie Cloud','quelle','https://www.iso.org/standard/43757.html','stufe','SOLL')),
  ('ISO27018','ISO27018-A.1.1','Zweckbindung: PII nur fuer vertraglich vereinbarte Zwecke verarbeiten.','Purpose limitation: process PII only for contractual purposes.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27018:2019 A.1.1 — Zweckbindung','quelle','https://www.iso.org/standard/76559.html','stufe','MUSS')),
  ('ISO27018','ISO27018-A.5.1','Kein Einsatz von PII fuer Marketing/Werbung ohne explizite Einwilligung.','No use of PII for marketing without explicit consent.',1,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27018:2019 A.5.1 — Marketing-Verbot','quelle','https://www.iso.org/standard/76559.html','stufe','MUSS')),
  ('ISO27018','ISO27018-A.9.2','Transparenz ueber Unterauftragsverarbeiter (Namen, Standorte, Kategorien).','Transparency on sub-processors (names, locations, categories).',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27018:2019 A.9.2 — Subprocessor-Transparenz','quelle','https://www.iso.org/standard/76559.html','stufe','MUSS')),
  ('ISO27018','ISO27018-A.10.1','Offenlegung der geografischen PII-Speicherorte an Kunden.','Disclosure of geographic PII storage locations to customers.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27018:2019 A.10.1 — Geo-Transparenz','quelle','https://www.iso.org/standard/76559.html','stufe','MUSS')),
  ('ISO27018','ISO27018-A.11.1','Meldung von PII-Breaches an Kunden binnen vertraglich definierter Frist.','Notify customers of PII breaches within contractually defined period.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27018:2019 A.11.1 — Breach-Meldung','quelle','https://www.iso.org/standard/76559.html','stufe','MUSS')),
  ('ISO27018','ISO27018-A.12.1','Rueckgabe/Loeschung von PII am Vertragsende mit dokumentiertem Nachweis.','Return/deletion of PII at contract end with documented evidence.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 27018:2019 A.12.1 — PII-Loeschung','quelle','https://www.iso.org/standard/76559.html','stufe','MUSS')),
  ('ISO42001','ISO42001-5.2','AI-Policy dokumentieren und durch Top-Management genehmigen.','Document and approve AI policy by top management.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 §5.2 — AI Policy','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-5.3','Rollen fuer AI-Governance zuweisen (AI-Owner, AI-Risk-Officer, AI-Ethik-Beauftragter).','Assign AI governance roles (owner, risk officer, ethics officer).',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 §5.3 — Rollen AI-Governance','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-6.1.4','AI-Risikoassessment mit spezifischen Kriterien: Bias, Erklaerbarkeit, Robustheit, Sicherheit.','AI risk assessment with specific criteria: bias, explainability, robustness, security.',4,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 §6.1.4 — AI-Risikoassessment','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-8.3','AI Impact Assessment fuer betroffene Individuen, Gruppen und Gesellschaft.','AI impact assessment for affected individuals, groups and society.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 §8.3 — Impact Assessment','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-A.6.2','Human Oversight fuer AI-Entscheidungen mit Interventionsmoeglichkeit.','Human oversight for AI decisions with intervention capability.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 Annex A.6.2 — Human Oversight','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-A.7.4','Trainingsdaten-Qualitaet: Herkunft, Bias-Pruefung, Repraesentativitaet.','Training data quality: provenance, bias checks, representativeness.',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 Annex A.7.4 — Datenqualitaet','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-A.8.2','Transparenz: Nutzer ueber AI-Interaktion informieren.','Transparency: inform users about AI interactions.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 Annex A.8.2 — Transparenz','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-A.9.2','Third-Party-AI-Systeme: Due Diligence, vertragliche Absicherung.','Third-party AI systems: due diligence, contractual safeguards.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 Annex A.9.2 — Third-Party AI','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-A.10.2','Kontinuierliches Monitoring von AI-Systemen im Betrieb (Drift, Performance).','Continuous monitoring of AI systems in operation (drift, performance).',3,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 Annex A.10.2 — AI Monitoring','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS')),
  ('ISO42001','ISO42001-9.2','Internes AI-Audit-Programm mit dokumentierten Feststellungen.','Internal AI audit programme with documented findings.',2,
   jsonb_build_object('coverage','delta','ref','ISO/IEC 42001:2023 §9.2 — Internes Audit','quelle','https://www.iso.org/standard/81230.html','stufe','MUSS'))
ON CONFLICT (framework, id) DO UPDATE SET
  req_de = EXCLUDED.req_de,
  req_en = EXCLUDED.req_en,
  effort_pt = EXCLUDED.effort_pt,
  meta = public.controls.meta || EXCLUDED.meta;
