/**
 * Remap controlCatalog (cid → measures+risks) into zokCatalog (ZOK → measures+risks).
 *
 * Deterministic — no AI calls. Uses controlMetadata.familyId to route each control's
 * measures/risks into the BSI Grundschutz++ Zielobjektkategorien.
 *
 * Output: src/data/zokCatalog.ts
 *
 * Run: bun run scripts/remap_catalog_to_zok.ts
 */

import { writeFileSync } from "fs";
import { controlCatalog, type CatalogMeasure, type CatalogRisk } from "../src/data/controlCatalog";
import { controlMetadata } from "../src/data/controlMetadata";
import type { ZokId } from "../src/data/zielobjektkategorien";

// ── Family → ZOK target categories ──
// A family's measures/risks are attached to the LEAF-most ZOKs that match its
// scope. Vererbung in the engine will propagate them to descendants automatically.
// Families like "governance" / "risk_mgmt" / "compliance_audit" are ISMS-wide
// (verbundweit) and get the special key "__isms__".
const FAMILY_TO_ZOKS: Record<string, (ZokId | "__isms__")[]> = {
  // Verbundweite ISMS-Anforderungen (organization-wide)
  governance:           ["__isms__"],
  risk_mgmt:            ["__isms__"],
  compliance_audit:     ["__isms__"],
  supplier_security:    ["__isms__"],
  business_continuity:  ["__isms__"],

  // Asset-Management gilt verbundweit + an konkreten Asset-Klassen
  asset_mgmt:           ["__isms__", "hostsysteme", "endgeraete", "anwendungen", "daten"],

  // Incident Response: Plan ist verbundweit, aber Playbooks/Detection greifen an Assets
  incident_mgmt:        ["__isms__", "hostsysteme", "anwendungen", "endgeraete", "netze_intern", "netze_extern"],

  // Personen / Rollen
  identity_access_mgmt: ["nutzende", "administrierende", "anwendungen", "hostsysteme"],
  personnel_security:   ["mitarbeitende"],
  awareness_training:   ["mitarbeitende"],

  // Netze (inkl. WLAN-Spezifika via Vererbung)
  network_security:     ["netze_intern", "netze_extern", "wlans"],

  // Endpoints (mobiles via Vererbung)
  endpoint_security:    ["endgeraete", "mobiltelefone"],

  // Monitoring/Detection muss auch auf Netzen greifen (IDS/NDR)
  monitoring_logging:   ["hostsysteme", "anwendungen", "endgeraete", "netze_intern", "netze_extern"],

  // Vulnerability/Patch — auch Web + Netzkomponenten
  vulnerability_mgmt:   ["hostsysteme", "endgeraete", "anwendungen", "webanwendungen", "netze_intern", "netze_extern"],

  // Krypto: Daten + Anwendungen + Transport (TLS/VPN auf Netzen)
  cryptography:         ["daten", "anwendungen", "netze_intern", "netze_extern"],

  // Datenschutz / DLP
  data_protection:      ["daten", "anwendungen", "webanwendungen"],

  // Sichere Entwicklung / Web
  secure_development:   ["webanwendungen", "anwendungen"],

  // Physische Sicherheit
  physical_security:    ["serverraeume", "raeume_techn_infra", "datentraegerarchiv", "gebaeude"],

  // MFA & Strong Authentication — identitätstragende Assets
  mfa_strong_auth:      ["nutzende", "administrierende", "anwendungen", "hostsysteme"],
};

interface ZokBucket {
  measures: Map<string, CatalogMeasure>;
  risks: Map<string, CatalogRisk>;
}

const buckets = new Map<ZokId | "__isms__", ZokBucket>();
function bucket(key: ZokId | "__isms__"): ZokBucket {
  let b = buckets.get(key);
  if (!b) { b = { measures: new Map(), risks: new Map() }; buckets.set(key, b); }
  return b;
}

// ── Iterate every control, route into target ZOKs ──
let routed = 0, skipped = 0;
for (const [cid, entry] of Object.entries(controlCatalog)) {
  const meta = controlMetadata[cid];
  if (!meta) { skipped++; continue; }
  const targets = FAMILY_TO_ZOKS[meta.familyId];
  if (!targets || targets.length === 0) { skipped++; continue; }

  for (const tgt of targets) {
    const b = bucket(tgt);
    for (const m of entry.measures) {
      // Dedupe by id; if collision, keep the first (catalog order is stable)
      if (!b.measures.has(m.id)) b.measures.set(m.id, m);
    }
    for (const r of entry.risks) {
      if (!b.risks.has(r.id)) b.risks.set(r.id, r);
    }
  }
  routed++;
}

// ── Build output object ──
const out: Record<string, { measures: CatalogMeasure[]; risks: CatalogRisk[] }> = {};
for (const [key, b] of buckets) {
  out[key] = {
    measures: [...b.measures.values()],
    risks: [...b.risks.values()],
  };
}

const sortedKeys = Object.keys(out).sort();
const sortedOut: typeof out = {};
for (const k of sortedKeys) sortedOut[k] = out[k];

const header = `/**
 * ZOK Catalog — Auto-generated by scripts/remap_catalog_to_zok.ts
 *
 * Maps each BSI Grundschutz++ Zielobjektkategorie (ZOK) to a deduplicated
 * set of concrete measures (Maßnahmen) and typical risks (Risiken),
 * sourced from the existing controlCatalog (ISO 27002 + BSI IT-Grundschutz).
 *
 * Special key "__isms__" holds verbundweite (organization-wide) ISMS
 * requirements that are NOT tied to a specific asset/ZOK (governance,
 * risk management, supplier security, business continuity, etc.).
 *
 * DO NOT EDIT BY HAND — regenerate via the script.
 */

import type { CatalogMeasure, CatalogRisk } from "./controlCatalog";
import type { ZokId } from "./zielobjektkategorien";

export type ZokCatalogKey = ZokId | "__isms__";

export interface ZokCatalogEntry {
  measures: CatalogMeasure[];
  risks: CatalogRisk[];
}

export const zokCatalog: Record<string, ZokCatalogEntry> = `;

const body = JSON.stringify(sortedOut, null, 2);
const footer = `;

export const ISMS_CATALOG_KEY = "__isms__" as const;
`;

writeFileSync("src/data/zokCatalog.ts", header + body + footer, "utf-8");

// ── Stats ──
console.log(`✓ Routed: ${routed} controls`);
console.log(`✗ Skipped: ${skipped} controls (no metadata or family mapping)`);
console.log(`\nZOK buckets:`);
for (const k of sortedKeys) {
  const e = sortedOut[k];
  console.log(`  ${k.padEnd(28)} measures=${String(e.measures.length).padStart(3)}  risks=${String(e.risks.length).padStart(3)}`);
}
