/**
 * Canonical BGBl. source-of-truth for BSIG Anlage 1 & 2.
 *
 * Source: Gesetz über das Bundesamt für Sicherheit in der Informationstechnik
 * und über die Sicherheit in der Informationstechnik von Einrichtungen (BSIG),
 * BGBl. 2025 I Nr. 301 — Anlage 1 (S. 45–47) und Anlage 2 (S. 47–48).
 *
 * This file is the verbatim structural reference. The rendered data in
 * `bsigSectors.ts` is reconciled against it by `lib/bsigReconciliation.ts`,
 * so any structural drift (missing sector, renamed sector, dropped branche
 * or einrichtungsart) is surfaced in the UI immediately.
 *
 * DO NOT edit this file to "fix" a UI bug — fix the rendered data instead.
 * This file may only be updated to track a new official BGBl amendment.
 */

export interface CanonicalEinrichtungsart {
  id: string;
}

export interface CanonicalBranche {
  id: string;
  name: string;
  einrichtungsartIds: string[];
}

export interface CanonicalSektor {
  nr: string;
  name: string;
  branchen: CanonicalBranche[];
}

export interface CanonicalAnlage {
  id: "anlage1" | "anlage2";
  title: string;
  expectedSectorCount: number;
  sektoren: CanonicalSektor[];
}

// ── Anhang I NIS2 — 11 Sektoren mit hoher Kritikalität (wesentliche Einrichtungen) ──
// Source: Directive (EU) 2022/2555, Annex I — verbatim sector/subsector structure.
export const canonicalAnlage1: CanonicalAnlage = {
  id: "anlage1",
  title: "Anhang I NIS2 — Sektoren mit hoher Kritikalität",
  expectedSectorCount: 11,
  sektoren: [
    {
      nr: "1", name: "Energie",
      branchen: [
        { id: "1.1", name: "Elektrizität",
          einrichtungsartIds: ["1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7"] },
        { id: "1.2", name: "Fernwärme und Fernkälte",
          einrichtungsartIds: ["1.2.1"] },
        { id: "1.3", name: "Erdöl",
          einrichtungsartIds: ["1.3.1","1.3.2","1.3.3"] },
        { id: "1.4", name: "Erdgas",
          einrichtungsartIds: ["1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7"] },
        { id: "1.5", name: "Wasserstoff",
          einrichtungsartIds: ["1.5.1"] },
      ],
    },
    {
      nr: "2", name: "Verkehr",
      branchen: [
        { id: "2.1", name: "Luftverkehr", einrichtungsartIds: ["2.1.1","2.1.2","2.1.3"] },
        { id: "2.2", name: "Schienenverkehr", einrichtungsartIds: ["2.2.1","2.2.2"] },
        { id: "2.3", name: "Schifffahrt", einrichtungsartIds: ["2.3.1","2.3.2","2.3.3"] },
        { id: "2.4", name: "Straßenverkehr", einrichtungsartIds: ["2.4.1","2.4.2"] },
      ],
    },
    {
      nr: "3", name: "Bankwesen",
      branchen: [{ id: "3.1", name: "Bankwesen", einrichtungsartIds: ["3.1.1"] }],
    },
    {
      nr: "4", name: "Finanzmarktinfrastrukturen",
      branchen: [{ id: "4.1", name: "Finanzmarktinfrastrukturen", einrichtungsartIds: ["4.1.1","4.1.2"] }],
    },
    {
      nr: "5", name: "Gesundheitswesen",
      branchen: [{ id: "5.1", name: "Gesundheitswesen", einrichtungsartIds: ["5.1.1","5.1.2","5.1.3","5.1.4","5.1.5"] }],
    },
    {
      nr: "6", name: "Trinkwasser",
      branchen: [{ id: "6.1", name: "Trinkwasser", einrichtungsartIds: ["6.1.1"] }],
    },
    {
      nr: "7", name: "Abwasser",
      branchen: [{ id: "7.1", name: "Abwasser", einrichtungsartIds: ["7.1.1"] }],
    },
    {
      nr: "8", name: "Digitale Infrastruktur",
      branchen: [{ id: "8.1", name: "Digitale Infrastruktur",
        einrichtungsartIds: ["8.1.1","8.1.2","8.1.3","8.1.4","8.1.5","8.1.6","8.1.7","8.1.8","8.1.9"] }],
    },
    {
      nr: "9", name: "Verwaltung von IKT-Diensten (Business-to-Business)",
      branchen: [{ id: "9.1", name: "Verwaltung von IKT-Diensten", einrichtungsartIds: ["9.1.1","9.1.2"] }],
    },
    {
      nr: "10", name: "Öffentliche Verwaltung",
      branchen: [{ id: "10.1", name: "Öffentliche Verwaltung", einrichtungsartIds: ["10.1.1","10.1.2"] }],
    },
    {
      nr: "11", name: "Weltraum",
      branchen: [{ id: "11.1", name: "Weltraum", einrichtungsartIds: ["11.1.1"] }],
    },
  ],
};

// ── Anhang II NIS2 — 7 Sektoren „sonstige kritische Sektoren" (wichtige Einrichtungen) ──
// Source: Directive (EU) 2022/2555, Annex II — verbatim sector/subsector structure.
export const canonicalAnlage2: CanonicalAnlage = {
  id: "anlage2",
  title: "Anhang II NIS2 — Sonstige kritische Sektoren (wichtige Einrichtungen)",
  expectedSectorCount: 7,
  sektoren: [
    {
      nr: "1", name: "Post- und Kurierdienste",
      branchen: [{ id: "1.1", name: "Post- und Kurierdienste", einrichtungsartIds: ["1.1.1"] }],
    },
    {
      nr: "2", name: "Abfallbewirtschaftung",
      branchen: [{ id: "2.1", name: "Abfallbewirtschaftung", einrichtungsartIds: ["2.1.1"] }],
    },
    {
      nr: "3", name: "Produktion, Herstellung und Handel mit chemischen Stoffen",
      branchen: [{ id: "3.1", name: "Produktion, Herstellung und Handel mit chemischen Stoffen", einrichtungsartIds: ["3.1.1"] }],
    },
    {
      nr: "4", name: "Produktion, Verarbeitung und Vertrieb von Lebensmitteln",
      branchen: [{ id: "4.1", name: "Produktion, Verarbeitung und Vertrieb von Lebensmitteln", einrichtungsartIds: ["4.1.1"] }],
    },
    {
      nr: "5", name: "Verarbeitendes Gewerbe / Herstellung von Waren",
      branchen: [
        { id: "5.1", name: "Herstellung von Medizinprodukten und In-vitro-Diagnostika", einrichtungsartIds: ["5.1.1"] },
        { id: "5.2", name: "Herstellung von Datenverarbeitungsgeräten, elektronischen und optischen Erzeugnissen", einrichtungsartIds: ["5.2.1"] },
        { id: "5.3", name: "Herstellung von elektrischen Ausrüstungen", einrichtungsartIds: ["5.3.1"] },
        { id: "5.4", name: "Maschinenbau (a.n.g.)", einrichtungsartIds: ["5.4.1"] },
        { id: "5.5", name: "Herstellung von Kraftwagen, Anhängern und Sattelanhängern", einrichtungsartIds: ["5.5.1"] },
        { id: "5.6", name: "Sonstiger Fahrzeugbau", einrichtungsartIds: ["5.6.1"] },
      ],
    },
    {
      nr: "6", name: "Anbieter digitaler Dienste",
      branchen: [{ id: "6.1", name: "Anbieter digitaler Dienste", einrichtungsartIds: ["6.1.1","6.1.2","6.1.3"] }],
    },
    {
      nr: "7", name: "Forschung",
      branchen: [{ id: "7.1", name: "Forschung", einrichtungsartIds: ["7.1.1"] }],
    },
  ],
};

export const canonicalSourceCitation = "Richtlinie (EU) 2022/2555 — Anhang I (Sektoren mit hoher Kritikalität) · Anhang II (sonstige kritische Sektoren)";
